# Generated by Django 4.1.7 on 2023-02-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rules', models.CharField(max_length=1000)),
                ('team_event', models.BooleanField(default=False)),
                ('team_min', models.IntegerField(default=0)),
                ('team_max', models.IntegerField(default=0)),
                ('pay', models.IntegerField(default=0)),
                ('max_reg', models.IntegerField(default=1000000000)),
                ('upload', models.BooleanField(default=False)),
                ('registrations', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
