# Generated by Django 4.1.7 on 2023-02-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
    ]
