# Generated by Django 4.1.7 on 2023-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_event_category_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collegename',
            field=models.CharField(default='REC', max_length=100),
            preserve_default=False,
        ),
    ]
