# Generated by Django 4.1.7 on 2023-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_user_collegename'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('day1', models.BooleanField()),
                ('day2', models.BooleanField()),
                ('day3', models.BooleanField()),
                ('day1Scan', models.IntegerField()),
                ('day2Scan', models.IntegerField()),
                ('day3Scan', models.IntegerField()),
            ],
        ),
    ]
