# Generated by Django 3.2.4 on 2023-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_mainevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('event_id', models.IntegerField()),
                ('team_mates', models.CharField(max_length=5000)),
                ('upload_link', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='day1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='day1Scan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='day2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='day2Scan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='day3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='day3Scan',
            field=models.IntegerField(default=0),
        ),
    ]
