# Generated by Django 3.2.4 on 2023-02-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20230223_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
