# Generated by Django 3.2.4 on 2023-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20230223_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainevent',
            name='day1Image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='day2Image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='day3Image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
