# Generated by Django 3.2.4 on 2023-02-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_eventregister_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='team_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
