# Generated by Django 4.1.7 on 2023-02-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_eventregister_team_mates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_mate', models.CharField(max_length=100)),
                ('event_register_id', models.IntegerField()),
            ],
        ),
    ]
