# Generated by Django 4.1.7 on 2023-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_teammates'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammates',
            name='event_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
