# Generated by Django 4.1.7 on 2023-02-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainevent',
            name='combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
