# Generated by Django 4.1.7 on 2023-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_category_event_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='premimumticket',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
