# Generated by Django 4.1.7 on 2023-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
