# Generated by Django 4.1.7 on 2023-03-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_transaction_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregister',
            name='pay_there',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammates',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
