# Generated by Django 4.1.7 on 2023-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_category_image_url_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='email_of_incharge',
            new_name='contact_mail',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name_of_incharge',
            new_name='name_of_incharge1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='phone_of_incharge',
            new_name='name_of_incharge2',
        ),
        migrations.AddField(
            model_name='event',
            name='name_of_incharge3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_of_incharge1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_of_incharge2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_of_incharge3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='selection',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.CharField(max_length=5000),
        ),
    ]
