# Generated by Django 4.1.7 on 2023-03-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_rename_email_of_incharge_event_contact_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='selection_procedure',
        ),
    ]
