# Generated by Django 4.1.7 on 2023-04-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_merch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneno',
            field=models.CharField(default=1234567890, max_length=100),
            preserve_default=False,
        ),
    ]
