# Generated by Django 4.2 on 2023-04-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='merch',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='premimumticket',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammates',
            name='team_mate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
